const ROLES = {
  ADMIN: "ADMIN",
  SUB_ADMIN: "SUB_ADMIN",
  HEAD_HR: "HEAD_HR",
  HEAD_HR_PUBLISHING: "HEAD_HR_PUBLISHING",
  HEAD_HR_NON_PUBLISHING: "HEAD_HR_NON_PUBLISHING",
  GROUP_MANAGER: "GROUP_MANAGER",
  MANAGER: "MANAGER",
  SUB_GROUP_MANAGER: "SUB_GROUP_MANAGER",
  STUDENT: "STUDENT"
};

const ROLE_LEVELS = {
  ADMIN: 100,
  SUB_ADMIN: 90,
  HEAD_HR: 80,
  HEAD_HR_PUBLISHING: 80,
  HEAD_HR_NON_PUBLISHING: 80,
  GROUP_MANAGER: 70,
  MANAGER: 70,
  SUB_GROUP_MANAGER: 60,
  STUDENT: 10
};

module.exports = {
  ROLES,
  ROLE_LEVELS
};